server:
  address: 127.0.0.1
  port: 8090
  forward-headers-strategy: NATIVE
spring:
  jpa:
    open-in-view: false
    show-sql: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true